### ISSUE TITLE
TypeError: Cannot read property '[object Array]' of undefined

### ISSUE THREAD

**Issue by scottinet** [kuzzleio/koncorde#13]
# Steps to reproduce

```js
const Koncorde = require('koncorde');

const foo = new Koncorde();

const p = foo.register('i', 'c', {equals: {bar: 'baz'}});
p.then(() => foo.test('i', 'c', {bar: ['baz']}));
```

Result:

```
TypeError: Cannot read property '[object Array]' of undefined
    at Object.MatchEquals [as equals] (/home/scottinet/git/kuzzle/node_modules/koncorde/lib/match/matchEquals.js:45:61)
    at Matcher.match (/home/scottinet/git/kuzzle/node_modules/koncorde/lib/match/index.js:64:29)
    at Koncorde.test (/home/scottinet/git/kuzzle/node_modules/koncorde/lib/index.js:148:27)
```

Koncorde does not expect a type Array when testing the `equals` operator.

**Comment by scottinet** [comment]
Will be naturally be fixed with the implementation of https://github.com/kuzzleio/koncorde/issues/14
