### ISSUE TITLE
geoBoundingBox query not accepting LatLon

### ISSUE THREAD

**Issue by keval-d** [kuzzleio/koncorde#42]
I'm using geoBoundingBox query for realtime event update for user with LatLon bound from google map coordinates.

## Expected Behavior
It can work with koncorde also

## Current Behavior
Work with elasticsearch **geo_bounding_box** but not in koncorde **geoBoundingBox**

## Possible Solution
-

## Steps to Reproduce
```
filter = {
  "bool": {
    "must": [
      { "equals": { "channelId": "QOWaqXMBR2Wv7hZ0DixN" } },
      {
        "geoBoundingBox": {
          "location": {
            "topLeft": {
              "lat": 21.16407700671505,
              "lon": 72.8233353048563
            },
            "bottomRight": {
              "lat": 21.176402562168704,
              "lon": 72.83878449350595
            }
          }
        }
      }
    ]
  }
}

app.sdk.realtime.subscribe('now', 'test', filter, (notification: DocumentNotification) => {
  app.log.info(`${notification.result._id} -> ${JSON.stringify(notification.result._source)}`)
})

```
![image](https://user-images.githubusercontent.com/68364421/107749454-a5af5d80-6d40-11eb-8f54-33f4e993ac2d.png)
From this: http://bboxfinder.com/#21.16407700671505,72.8233353048563,21.176402562168704,72.83878449350595

Error from console:
kuzzle_1         | error: 2021-02-12T09:11:10+00:00 [LOG:ERROR] [healthy-toucan-1834] ERROR: unhandledRejection: min_lat argument cannot be greater or equal max_lat. Reason: Error: 
kuzzle_1         |     at FunnelProtocol.query (/var/app/node_modules/kuzzle/lib/core/shared/sdk/funnelProtocol.js:63:15)
kuzzle_1         |     at EmbeddedSDK.query (/var/app/node_modules/kuzzle-sdk/src/Kuzzle.js:390:30)
kuzzle_1         |     at EmbeddedSDK.query (/var/app/node_modules/kuzzle/lib/core/shared/sdk/embeddedSdk.js:71:22)
kuzzle_1         |     at Room.subscribe (/var/app/node_modules/kuzzle-sdk/src/core/Room.js:55:24)
kuzzle_1         |     at RealtimeController.subscribe (/var/app/node_modules/kuzzle-sdk/src/controllers/Realtime.js:129:21)
kuzzle_1         |     at /var/app/app.ts:79:30
kuzzle_1         |     at Array.forEach (<anonymous>)
kuzzle_1         |     at /var/app/app.ts:36:32
kuzzle_1         |     at Array.forEach (<anonymous>)
kuzzle_1         |     at /var/app/app.ts:35:27
kuzzle_1         |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
kuzzle_1         |     at /var/app/app.ts:33:5

## Context (Environment)
kuzzle: 2.9.1

**Comment by scottinet** [comment]
Hi!

It seems that you interverted the bottomRight and topLeft coordinates. What Koncorde is telling you is that the latitude of the topLeft coordinates is lower than the bottomRight one, which isn't consistent.

**Comment by keval-d** [comment]
What should I do?

**Comment by scottinet** [comment]
You can fix that by simply providing the right coordinates:

```json
filter = {
  "bool": {
    "must": [
      { "equals": { "channelId": "QOWaqXMBR2Wv7hZ0DixN" } },
      {
        "geoBoundingBox": {
          "location": {
            "topLeft": {
              "lat": 21.176402562168704,
              "lon": 72.8233353048563
            },
            "bottomRight": {
              "lat": 21.16407700671505,
              "lon": 72.83878449350595
            }
          }
        }
      }
    ]
  }
}
```

**Comment by scottinet** [comment]
Closing due to inactivity.
